### PR TITLE
feature: adds credits to footer

### PR DESCRIPTION
**Pull request by mb-wali**

### CODE REVIEW

**Comment by utnapischtim** [comment]
i am not happy with the German translation, but i need some time to find a better translation.

**Comment by utnapischtim** [comment]
is there also a logo for the fair data austria project? and could we add also some further logos there?

**Comment by mb-wali** [comment]
> is there also a logo for the fair data austria project? and could we add also some further logos there?

fair

better?

**Comment by utnapischtim** [comment]
yes, it is better, but is the logo little bit stretched in the vertical direction?

**Comment by mb-wali** [comment]
> yes, it is better, but is the logo little bit stretched in the vertical direction?

yes - the logo is too big: see here, if you it looks ok , we can leave it in full size:
unstreched

**Comment by mb-wali** [comment]
@utnapischtim what do you think to add also one of these badges:
https://www.re3data.org/resources/badge/100013565

**Comment by utnapischtim** [comment]
Please add the logo of https://www.openeducation.at/ right of the FAIR logo

Please don't translate "Powered by" and "Enabled by". I can't find for adequate German translations

**Comment by mb-wali** [comment]
## Update
updated

**Comment by utnapischtim** [comment]
The translation changes we could do also in a separated PR. I only saw some improvements and then i saw some more.

**Pull request merged**
